#!/bin/bash
# Helper script to set up GitHub secrets for CI/CD
# Generates commands you need to run to configure GitHub Actions

set -e

echo "🔐 GitHub Secrets Setup Guide"
echo "=============================="
echo ""
echo "To enable GitHub Actions CI/CD, you need to add secrets to your repository."
echo ""
echo "Option 1: Using GitHub CLI (gh)"
echo "================================"
echo ""

if command -v gh &> /dev/null; then
    echo "✅ GitHub CLI is installed"
    echo ""
    echo "Run these commands:"
    echo ""

    # Check if user is authenticated
    if gh auth status &> /dev/null; then
        echo "# You're authenticated with GitHub CLI"
        echo ""
        echo "# Set AWS credentials (you'll be prompted for values):"
        echo "gh secret set AWS_ACCESS_KEY_ID --repo reena96/plccoach"
        echo "gh secret set AWS_SECRET_ACCESS_KEY --repo reena96/plccoach"
        echo ""
        echo "# Set AWS region:"
        echo "gh secret set AWS_REGION --body 'us-east-1' --repo reena96/plccoach"
        echo ""
        echo "# Set ECR repository:"
        echo "gh secret set ECR_REPOSITORY --body '971422717446.dkr.ecr.us-east-1.amazonaws.com/plccoach/api' --repo reena96/plccoach"
        echo ""
    else
        echo "⚠️  You need to authenticate first:"
        echo "    gh auth login"
        echo ""
    fi
else
    echo "❌ GitHub CLI not installed"
    echo ""
    echo "Install with:"
    echo "  brew install gh              # macOS"
    echo "  sudo apt install gh          # Ubuntu/Debian"
    echo "  choco install gh             # Windows"
    echo ""
fi

echo ""
echo "Option 2: Using GitHub Web Interface"
echo "====================================="
echo ""
echo "1. Go to: https://github.com/reena96/plccoach/settings/secrets/actions"
echo "2. Click 'New repository secret'"
echo "3. Add each secret below:"
echo ""
echo "   Name: AWS_ACCESS_KEY_ID"
echo "   Value: <your AWS access key>"
echo ""
echo "   Name: AWS_SECRET_ACCESS_KEY"
echo "   Value: <your AWS secret key>"
echo ""
echo "   Name: AWS_REGION"
echo "   Value: us-east-1"
echo ""
echo "   Name: ECR_REPOSITORY"
echo "   Value: 971422717446.dkr.ecr.us-east-1.amazonaws.com/plccoach/api"
echo ""
echo ""
echo "How to Get AWS Credentials for GitHub Actions"
echo "=============================================="
echo ""
echo "Best Practice: Create a dedicated IAM user for GitHub Actions"
echo ""
echo "Run these AWS CLI commands:"
echo ""
echo "# 1. Create IAM user"
echo "aws iam create-user --user-name github-actions-plccoach"
echo ""
echo "# 2. Attach required policies"
echo "aws iam attach-user-policy \\"
echo "  --user-name github-actions-plccoach \\"
echo "  --policy-arn arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser"
echo ""
echo "aws iam attach-user-policy \\"
echo "  --user-name github-actions-plccoach \\"
echo "  --policy-arn arn:aws:iam::aws:policy/AmazonECS_FullAccess"
echo ""
echo "aws iam attach-user-policy \\"
echo "  --user-name github-actions-plccoach \\"
echo "  --policy-arn arn:aws:iam::aws:policy/SecretsManagerReadWrite"
echo ""
echo "# 3. Create access key"
echo "aws iam create-access-key --user-name github-actions-plccoach"
echo ""
echo "This will output your AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY"
echo "Save these securely - they won't be shown again!"
echo ""
echo ""
echo "Verification"
echo "============"
echo ""
echo "After adding secrets, verify they're set:"
echo "  gh secret list --repo reena96/plccoach"
echo ""
echo "Or check on GitHub:"
echo "  https://github.com/reena96/plccoach/settings/secrets/actions"
echo ""
echo "You should see:"
echo "  ✅ AWS_ACCESS_KEY_ID"
echo "  ✅ AWS_SECRET_ACCESS_KEY"
echo "  ✅ AWS_REGION"
echo "  ✅ ECR_REPOSITORY"
echo ""
